from __future__ import annotations

from datetime import time

SCORE_THRESHOLD = 0.45
STRONG_SIGNAL_THRESHOLD = 0.70
PREEMPTION_THRESHOLD = 0.85

TRIAL_RATIO_NORMAL = 0.30
TRIAL_RATIO_STRONG = 0.50

GAP_THRESHOLD_MIN = 0.01
GAP_ATR_FACTOR = 0.5

VWAP_WARMUP_END = time(9, 50)
VWAP_WARMUP_EXTEND_END = time(10, 0)

IOPV_PREMIUM_TRIAL = 0.005
IOPV_PREMIUM_CONFIRM = 0.003

MAX_POSITION_COUNT = 2
SINGLE_POSITION_CAP = 70000.0
COOLDOWN_DAYS = 5

PREEMPTION_MAX_AMOUNT = 40000.0
WEAK_PROFIT_PROTECTION = 0.02
WEAK_ATR_FACTOR = 0.5
WEAK_MIN_HOLD_DAYS = 3
PREEMPTION_SELL_TIMEOUT_MIN = 30
PREEMPTION_COOLDOWN_DAYS = 3

