from __future__ import annotations

from datetime import time

from core.constants import EXIT_BUYBACK_CUTOFF_TIME

SCORE_WEIGHTS: dict[str, float] = {
    "S_chip": 0.7,
    "S_sentiment": 0.7,
    "S_diverge": 0.5,
    "S_time": 0.4,
}

VALID_SIGNAL_KEYS = set(SCORE_WEIGHTS.keys())

LAYER2_THRESHOLD = 0.7

S_SENTIMENT_THRESHOLD = 0.35

S_CHIP_COLD_START_DAYS = 10
S_CHIP_PROFIT_RATIO_GATE = 75.0
S_CHIP_TIER1_DAILY_DROP_THRESHOLD = -0.15
S_CHIP_TIER2_DROP_DAYS_THRESHOLD = 3
S_CHIP_TIER3_TOTAL_DROP_THRESHOLD = -0.20
S_CHIP_DPC_EPS = 0.01
S_CHIP_ALLOWED_VALUES = (0.0, 0.3, 0.5, 0.7, 1.0)

RSI_PERIOD = 14
RSI_OVERBOUGHT_THRESHOLD = 65.0
RSI_PEAK_LEFT_RIGHT = 3
RSI_MIN_PEAK_GAP_DAYS = 5
RSI_DIVERGENCE_CONFIRM_DAYS = 3

ADX_PERIOD = 14
ADX_STRONG_TREND_THRESHOLD = 35.0

VOLUME_SHRINK_WINDOW_DAYS = 8
VOLUME_NEW_HIGH_LOOKBACK_DAYS = 5
VOLUME_MA_DAYS = 5
VOLUME_SHRINK_RATIO = 0.8
VOLUME_SHRINK_NEW_HIGH_MIN_COUNT = 2

S_TIME_MIN_DAYS_HELD = 15
S_TIME_MIN_DAYS_SINCE_HIGH = 6
S_TIME_MIN_RETURN = 0.05

ATR_PERIOD = 12

K_NORMAL = 2.8
K_CHIP_DECAY = 2.38
K_REDUCED = 1.5

STOP_BREAK_BUFFER_TICKS = 0
LIFEBOAT_BUYBACK_REENTRY_TICKS = 2

LAYER1_SELL_DISCOUNT = 0.98
LIFEBOAT_BUYBACK_UPLIFT = 1.003
LIFEBOAT_SELL_PCT = 0.70
LIFEBOAT_RETAIN_PCT = 0.30
LIFEBOAT_TIGHT_STOP_PCT = 0.01
LIFEBOAT_COOLDOWN_TRADING_MINUTES = 30
LIFEBOAT_DEAD_CAT_LIMITDOWN_MULTIPLIER = 1.02
LIFEBOAT_BUYBACK_CUTOFF_TIME: time = EXIT_BUYBACK_CUTOFF_TIME

GAP_STOP_MULTIPLIER = 0.97
GAP_CHECK_TIMES = (time(9, 25), time(13, 0))

DEADWATER_MIN_DAYS_HELD = 10
DEADWATER_MAX_ABS_RETURN = 0.02

T0_DAILY_LOSS_CIRCUIT_BREAKER_PCT = 0.003
